# Generated by Django 5.2.4 on 2025-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=64)),
                ('price', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('manufacturer', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('condition', models.CharField(max_length=64)),
                ('cylinders', models.CharField(max_length=64)),
                ('fuel', models.CharField(max_length=64)),
                ('odometer', models.PositiveSmallIntegerField()),
                ('title_status', models.CharField(max_length=64)),
                ('transmission', models.CharField(max_length=64)),
                ('drive', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('paint_color', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
            ],
        ),
    ]
