# Generated by Django 5.2.4 on 2025-07-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
